config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :questions

  resources :sessions

  get    'login'   => 'sessions#new', :as => "login"
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy', :as => "logout"

  root 'questions#index'

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
  validates :password, length: { in: 6..30 }

  has_many :questions

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Session successfully created"
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render "new"
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackoverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>


<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>.
    <%= link_to "Logout", logout_path, :method => :delete%>
  <% else %>
    <%= link_to "Sign up", new_user_path %> or
    <%= link_to "login", login_path %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/questions/index.html.erb
<% @questions.each do |question| %>
  <%=question.title %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <p>
      <%= f.label :username %><br>
      <%= f.text_field :username %>
   </p>

    <p>
      <%= f.label :email %><br>
      <%= f.email_field :email %>
   </p>

    <p>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
   </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <h2><%= link_to user.username.capitalize, user_path(user) %><br></h2>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1> Sign Up </h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.username.capitalize %>'s Page<br></h1>
<%= @user.email %>